#!/bin/bash

# BEGIN DEBIAN PACKAGES:

STEAMOS_COMPMGR_AMD64='steamos-compositor_1.35+bsos1_amd64.deb'
STEAMOS_COMPMGR_I386='steamos-compositor_1.35+bsos1_i386.deb'
STEAMOS_MODSWIN_AMD64='steamos-modeswitch-inhibitor_1.10+bsos1_amd64.deb'
STEAMOS_MODSWIN_I386='steamos-modeswitch-inhibitor_1.10+bsos1_i386.deb'
STEAMOS_PLYMOUTH='plymouth-themes-steamos_0.17+bsos2_all.deb'
STEAMOS_PLYMOUTH_ALIEN='plymouth-themes-steamos-branding-alienware_0.4+bsos2_all.deb'
UBUNTU_MULTI='multiarch-support_2.27-3ubuntu1.3_amd64.deb'

# END DEBIAN PACKAGES.

DEBDIR=/usr/src/

# Install SteamOS compositor
dpkg -i ${DEBDIR}${UBUNTU_MULTI}
dpkg -i ${DEBDIR}${STEAMOS_MODSWIN_AMD64}
dpkg -i ${DEBDIR}${STEAMOS_MODSWIN_I386}
dpkg -i ${DEBDIR}${STEAMOS_COMP_AMD64} || apt install -f

# Install SteamOS plymouth themes
dpkg -i ${DEBDIR}${STEAMOS_PLYMOUTH}

# Install SteamOS plymouth themes (Alienware)
dpkg -i ${DEBDIR}${STEAMOS_PLYMOUTH_ALIEN}
