#!/bin/bash

# BEGIN DEBIAN PACKAGES:

STEAMOS_COMPMGR_AMD64='steamos-compositor_1.35+bsos1_amd64.deb'
STEAMOS_COMPMGR_I386='steamos-compositor_1.35+bsos1_i386.deb'
STEAMOS_MODSWIN_AMD64='steamos-modeswitch-inhibitor_1.10+bsos1_amd64.deb'
STEAMOS_MODSWIN_I386='steamos-modeswitch-inhibitor_1.10+bsos1_i386.deb'
STEAMOS_PLYMOUTH='plymouth-themes-steamos_0.17+bsos2_all.deb'
STEAMOS_PLYMOUTH_ALIEN='plymouth-themes-steamos-branding-alienware_0.4+bsos2_all.deb'
UBUNTU_MULTI='multiarch-support_2.27-3ubuntu1.3_amd64.deb'

# END DEBIAN PACKAGES.

# Remove SteamOS compositor
dpkg --remove steamos-modswitch-inhibitor
dpkg --remove steamos-modswitch-inhibitor:i386
dpkg --remove steamos-compositor
