#!/bin/bash
#
## Pre-Installation for SteamOS (LTS)

set -e

## BEGIN STEAMOS LTS ENIRONMAENT:

define STEAMOS_USER steam
define DESKTOP_USER desktop

# END STEAMOS LTS ENVIRNMENT.

# Create SteamOS user.
adduser --gecos "" --disabled-password ${STEAMOS_USER}
usermod -a -G audio,dip,video,plugdev,netdev,bluetooth,pulse-access $(STEAMOS_USER)

# Install Steam client package.
apt install steam -y

# Create Linux desktop user.
adduser --gecos "" --disabled-password ${DESKTOP_USER}
usermod -a -G pulse-access ${DESKTOP_USER}

usermod -a -G ${DESKTOP_USER} ${STEAMOS_USER}

# Install LightDM.
apt install lightdm -y
apt purge gdm3 -y
apt autoremove -y

exit $?
